services:
  - type: web
    name: pulscord
    env: node
    plan: starter
    region: frankfurt
    buildCommand: npm install
    startCommand: node server.js
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATA_DIR
        value: /var/data
    disk:
      name: pulscord-data
      mountPath: /var/data
      sizeGB: 1
